spring:
  data:
    mongodb:
      username: alrawasabed
      password: alrawasabed
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090