services:
  postgresql:
    container_name: ms_pg_sql
    image: postgres:16
    environment:
      POSTGRES_USER: alrawasabed
      POSTGRES_PASSWORD: alrawasabed
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    restart: unless-stopped


  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - microservices-net

  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alrawasabed
      - MONGO_INITDB_ROOT_PASSWORD=alrawasabed
  

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  mongo:
